default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_bin
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: db

development:
  <<: *default
  database: rails_experiment_development

test:
  <<: *default
  database: restful_api_rails_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: restful_api_rails_production
