packages:
  - .

allowBuilds:
  unrs-resolver: true

ignoredBuiltDependencies:
  - core-js

overrides:
  'js-yaml@<=4.1.1': '^4.1.2'
  'brace-expansion@<=5.0.7': '^5.0.8'
  'minimatch@<10.2.2': '^10.2.5'
  'babel-plugin-istanbul@<8.0.2': '^8.0.2'
