# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby file: '.ruby-version'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 8.1.3'
# Use Puma as the app server
gem 'puma', '~> 8.0.1'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
gem 'bcrypt', '~> 3.1.22'

# Use MySQL as the database for Active Record
gem 'mysql2', '~> 0.5.7'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '~> 1.24.5', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

# JSON web tokens
gem 'jwt', '~> 3.2.0'

# Active model serializers
gem 'active_model_serializers', '~> 0.10.14'

# pagination
gem 'will_paginate', '~> 4.0.1'

# environmental variables
gem 'dotenv-rails', '~> 3.2.0'

gem 'net-smtp', '~> 0.5.0'

# The Observer pattern provides a simple mechanism for one object to inform
# a set of interested third-party objects when its state changes.
gem 'observer', '~> 0.1.2'

# Data structure, similar to a Hash, that allows the definition of arbitrary attributes with their accompanying values
gem 'ostruct', '~> 0.6.3'

group :development, :test do
  # Debug tool used with binding.irb. Explicit require avoids eager loading `debug/prelude`
  # which interferes with the Docker boot process.
  # [Ref] https://ruby.github.io/irb/#label-Debugging+with+IRB
  # [Ref] https://github.com/ruby/debug#debug-command-on-the-debug-console
  # [Ref] https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[mri windows], require: false
end

group :development do
  gem 'brakeman', '~> 8.0.4', require: false
  # RuboCop
  gem 'rubocop', '~> 1.86.2', require: false
  gem 'rubocop-factory_bot', '~> 2.28.0', require: false
  gem 'rubocop-performance', '~> 1.26.0', require: false
  gem 'rubocop-rails', '~> 2.35.2', require: false
  gem 'rubocop-rspec', '~> 3.9.0', require: false
  gem 'rubocop-rspec_rails', '~> 2.32.0', require: false
  # Typechecking
  gem 'rbs-inline', '~> 0.14.0', require: false
  gem 'rbs_rails', '~> 0.13.1', require: false
  gem 'steep', '~> 2.0.0', require: false
end

group :test do
  # 'factory_bot_rails' cames not to behave right in 5.0 or more
  gem 'database_cleaner', '~> 2.1.0'
  gem 'factory_bot_rails', '~> 6.5.1'
  gem 'faker', '~> 3.8.0'
  gem 'rspec-rails', '~> 8.0.4'
  gem 'shoulda-matchers', '~> 7.0.1'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[windows jruby]
