source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.3.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 7.1.3.2'
# Use Puma as the app server
gem 'puma', '~> 6.0.1'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
gem 'bcrypt', '~> 3.1.20'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '~> 1.16.0', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

# JSON web tokens
gem 'jwt', '~> 2.7.1'

# Active model serializers
gem 'active_model_serializers', '~> 0.10.14'

# pagination
gem 'will_paginate', '~> 3.3.1'

# environmental variables
gem 'dotenv-rails', '~> 2.8.1'

gem 'nokogiri', '~> 1.16.3'

gem 'net-smtp', '~> 0.3.3'

group :development, :test do
  # Use MySQL as the database for Active Record
  gem 'mysql2', '~> 0.5.6'

  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', '~> 11.1.3', platforms: [:mri, :mingw, :x64_mingw]

  # Debug
  gem 'pry-rails'
end

group :development do
  gem 'listen', '~> 3.8.0'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring', '~> 4.1.0'
  gem 'spring-watcher-listen', '~> 2.1.0'
end

group :test do
  # 'factory_bot_rails' cames not to behave right in 5.0 or more
  gem 'factory_bot_rails', '~> 6.2.0'
  gem 'rspec-rails', '~> 6.0.4'
  gem 'faker', '~> 3.1.1'
  gem 'shoulda-matchers', '~> 5.3.0'
  gem 'database_cleaner', '~> 2.0.1'
end

group :production do
  gem 'pg', '~> 1.4.6'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
