source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby file: '.ruby-version'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 8.1.3'
# Use Puma as the app server
gem 'puma', '~> 8.0.0'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
gem 'bcrypt', '~> 3.1.22'

# Use MySQL as the database for Active Record
gem 'mysql2', '~> 0.5.7'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '~> 1.23.0', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

# JSON web tokens
gem 'jwt', '~> 3.1.2'

# Active model serializers
gem 'active_model_serializers', '~> 0.10.14'

# pagination
gem 'will_paginate', '~> 4.0.1'

# environmental variables
gem 'dotenv-rails', '~> 3.2.0'

gem 'nokogiri', '~> 1.19.2'

gem 'net-smtp', '~> 0.5.0'

# The Observer pattern provides a simple mechanism for one object to inform a set of interested third-party objects when its state changes.
gem 'observer', '~> 0.1.2'

# Data structure, similar to a Hash, that allows the definition of arbitrary attributes with their accompanying values
gem 'ostruct', '~> 0.6.3'

# A foreign function interface (FFI) is a mechanism by which a program written in one programming language can call routines or make use of services written or compiled in another one
gem 'ffi', '~> 1.17.4'

group :development, :test do
  # Debug tool used with binding.irb. Explicit require avoids eager loading `debug/prelude`
  # which interferes with the Docker boot process.
  # [Ref] https://ruby.github.io/irb/#label-Debugging+with+IRB
  # [Ref] https://github.com/ruby/debug#debug-command-on-the-debug-console
  # [Ref] https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[ mri windows ], require: false
end

group :development do
  gem 'brakeman', '~> 8.0.4', require: false
end

group :test do
  # 'factory_bot_rails' cames not to behave right in 5.0 or more
  gem 'factory_bot_rails', '~> 6.5.1'
  gem 'rspec-rails', '~> 8.0.4'
  gem 'faker', '~> 3.6.0'
  gem 'shoulda-matchers', '~> 7.0.1'
  gem 'database_cleaner', '~> 2.1.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:windows, :jruby]
