inherit_from: .rubocop_todo.yml

# Reference: https://github.com/rubocop/ruby-style-guide

plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 4.0
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'
