source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby file: '.ruby-version'

# Rails 8.1
gem 'rails', '~> 8.1.3'
# Use mysql2 as the database for Active Record
gem 'mysql2', '~> 0.5.7'
# Use Puma as the app server
gem 'puma', '~> 8.0.0'
# Use Propshaft as the asset pipeline
gem 'propshaft', '~> 1.3.1'
# Use importmap for JavaScript
gem 'importmap-rails', '~> 2.2.3'
# Hotwire's modest JavaScript framework
gem 'turbo-rails', '~> 2.0.16'
# Build JSON APIs with ease
gem 'jbuilder', '~> 2.14.1'
# Use Active Model has_secure_password
gem 'bcrypt', '~> 3.1.22'

gem 'devise', '~> 5.0.3'
gem 'enum_help'
# environment variables
gem 'dotenv-rails', '~> 3.2.0'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '~> 1.23.0', require: false

group :development, :test do
  gem 'debug', platforms: %i[ mri windows ], require: false
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '~> 4.3.0'
  # Static code analysis for security vulnerabilities
  gem 'brakeman', '~> 8.0.4', require: false
  # RuboCop
  gem 'rubocop', require: false
  gem 'rubocop-minitest', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false

  # Provides methods for benchmarking Ruby code, giving detailed reports on the time taken for each task
  gem 'benchmark', '~> 0.5.0'
end

group :test do
  gem 'factory_bot_rails', '~> 6.5.1'
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '~> 3.40.0'
  gem 'selenium-webdriver', '~> 4.43.0'
  gem 'matrix', '~> 0.4.2'
  gem 'rails-controller-testing', '~> 1.0.5'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:windows, :jruby]
