source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby file: '.ruby-version'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 7.1.3.4'
# Use Puma as the app server
gem 'puma', '~> 6.4.2'
# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem 'sprockets-rails', '~> 3.4.2'
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker', '~> 5.4.3'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbo-rails', '~> 1.4.0'
# Use Sass to process CSS
gem 'sassc-rails', '~> 2.1.2'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.11.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
gem 'image_processing', '~> 1.12.2'

gem 'active_storage_validations', '~> 1.0.4'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '~> 1.16.0', require: false

# Error tracking
gem 'rollbar', '~> 3.4.2'

# environmental variables
gem 'dotenv-rails', '~> 2.8.1'

# OAuth
gem 'omniauth', '~> 2.1.0'
gem 'omniauth-github', '~> 2.0.1'
gem 'omniauth-rails_csrf_protection', '~> 1.0.1'

# Locale
gem 'rails-i18n', '~> 7.0.9'

# Pagination
gem 'kaminari', '~> 1.2.2'

# SearchForm
gem 'ransack', '~> 4.0.0'

gem 'rexml', '~> 3.3.2'

gem 'nokogiri', '~> 1.16.6'

# YAML parser
gem 'psych', '~> 5.1.0'

gem 'net-smtp', '~> 0.5.0'

# The Observer pattern provides a simple mechanism for one object to inform a set of interested third-party objects when its state changes.
gem 'observer', '~> 0.1.2'

group :development, :test do
  # Use mysql as the database for Active Record
  gem 'mysql2', '~> 0.5.6'
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', '~> 11.1.3', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '~> 4.2.0'
  gem 'listen', '~> 3.8.0'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring', '~> 4.1.3'
end

group :test do
  gem 'factory_bot_rails', '~> 6.2.0'
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '~> 3.38.0'
  gem 'selenium-webdriver', '~> 4.8.6'
  # Easy installation and use of web drivers to run system tests with browsers
  gem 'webdrivers', '~> 5.2.0'
  gem 'matrix', '~> 0.4.2'
  gem 'pry-rails', '~> 0.3.11'
end

group :production do
  gem 'pg', '~> 1.4.5'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
