D = Steep::Diagnostic

target :app do
  check "app"
  check "test"
  signature "sig"

  library "minitest"
  library "net-smtp"
  library "observer"
  library "ostruct"
  library "psych"

  configure_code_diagnostics(D::Ruby.default)
end
