# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Brakeman - e-Navigator

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/brakeman--e-navigator.yml'
      - '.ruby-version'
      - 'ruby-on-rails/e-navigator/.ruby-version'
      - 'ruby-on-rails/e-navigator/Gemfile'
      - 'ruby-on-rails/e-navigator/Gemfile.lock'
      - 'ruby-on-rails/e-navigator/Rakefile'
      - 'ruby-on-rails/e-navigator/**/*.rb'
      - 'ruby-on-rails/e-navigator/**/*.rake'
      - 'ruby-on-rails/e-navigator/**/*.yml'
      - 'ruby-on-rails/e-navigator/**/*.js'
      - 'ruby-on-rails/e-navigator/**/*.scss'
      - 'ruby-on-rails/e-navigator/**/*.css'
      - 'ruby-on-rails/e-navigator/**/*.html.erb'
  pull_request:
    paths:
      - '.github/workflows/brakeman--e-navigator.yml'
      - '.ruby-version'
      - 'ruby-on-rails/e-navigator/.ruby-version'
      - 'ruby-on-rails/e-navigator/Gemfile'
      - 'ruby-on-rails/e-navigator/Gemfile.lock'
      - 'ruby-on-rails/e-navigator/Rakefile'
      - 'ruby-on-rails/e-navigator/**/*.rb'
      - 'ruby-on-rails/e-navigator/**/*.rake'
      - 'ruby-on-rails/e-navigator/**/*.yml'
      - 'ruby-on-rails/e-navigator/**/*.js'
      - 'ruby-on-rails/e-navigator/**/*.scss'
      - 'ruby-on-rails/e-navigator/**/*.css'
      - 'ruby-on-rails/e-navigator/**/*.html.erb'

permissions:
  contents: read

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
      # change this to (see https://github.com/ruby/setup-ruby#versioning):
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Bundle Install
        working-directory: ./ruby-on-rails/e-navigator
        run: |
          bundle config set --local path 'vendor/bundle'
          bundle install
      - name: Run Brakeman
        working-directory: ./ruby-on-rails/e-navigator
        run: bundle exec brakeman --no-pager
