# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: e-Navigator

on:
  push:
    branches:
      - master
    paths:
      - .github/actions/setup-ruby-on-rails/action.yml
      - .github/workflows/minitest--e-navigator.yml
      - .ruby-version
      - ruby-on-rails/e-navigator/.ruby-version
      - ruby-on-rails/e-navigator/Gemfile
      - ruby-on-rails/e-navigator/Gemfile.lock
      - ruby-on-rails/e-navigator/Rakefile
      - ruby-on-rails/e-navigator/rubocop.yml
      - ruby-on-rails/e-navigator/rubocop_todo.yml
      # - ruby-on-rails/e-navigator/Steepfile
      - ruby-on-rails/e-navigator/**/*.rb
      # - ruby-on-rails/e-navigator/**/*.rbs
      - ruby-on-rails/e-navigator/**/*.rake
      - ruby-on-rails/e-navigator/**/*.yml
      - ruby-on-rails/e-navigator/**/*.js
      - ruby-on-rails/e-navigator/**/*.scss
      - ruby-on-rails/e-navigator/**/*.css
      - ruby-on-rails/e-navigator/**/*.html.erb
  pull_request:
    paths:
      - .github/actions/setup-ruby-on-rails/action.yml
      - .github/workflows/minitest--e-navigator.yml
      - .ruby-version
      - ruby-on-rails/e-navigator/.ruby-version
      - ruby-on-rails/e-navigator/Gemfile
      - ruby-on-rails/e-navigator/Gemfile.lock
      - ruby-on-rails/e-navigator/Rakefile
      - ruby-on-rails/e-navigator/rubocop.yml
      - ruby-on-rails/e-navigator/rubocop_todo.yml
      # - ruby-on-rails/e-navigator/Steepfile
      - ruby-on-rails/e-navigator/**/*.rb
      # - ruby-on-rails/e-navigator/**/*.rbs
      - ruby-on-rails/e-navigator/**/*.rake
      - ruby-on-rails/e-navigator/**/*.yml
      - ruby-on-rails/e-navigator/**/*.js
      - ruby-on-rails/e-navigator/**/*.scss
      - ruby-on-rails/e-navigator/**/*.css
      - ruby-on-rails/e-navigator/**/*.html.erb

permissions:
  contents: read
  pull-requests: read

jobs:
  change-detection:
    runs-on: ubuntu-latest
    outputs:
      ruby-changes: ${{ steps.change-detection.outputs.ruby }}
      rubocop-changes: ${{ steps.change-detection.outputs.rubocop}}
      # steep-changes: ${{ steps.change-detection.outputs.steep}}
    steps:
      - uses: actions/checkout@v6
      - name: Change Detection
        uses: dorny/paths-filter@v4
        id: change-detection
        with:
          filters: |
            ruby:
              - .github/actions/setup-ruby-on-rails/action.yml
              - .github/workflows/minitest--e-navigator.yml
              - .ruby-version
              - ruby-on-rails/e-navigator/.ruby-version
              - ruby-on-rails/e-navigator/Gemfile
              - ruby-on-rails/e-navigator/Gemfile.lock
              - ruby-on-rails/e-navigator/Rakefile
              - ruby-on-rails/e-navigator/**/*.rb
              - ruby-on-rails/e-navigator/**/*.rake
              - ruby-on-rails/e-navigator/**/*.yml
              - ruby-on-rails/e-navigator/**/*.js
              - ruby-on-rails/e-navigator/**/*.scss
              - ruby-on-rails/e-navigator/**/*.css
              - ruby-on-rails/e-navigator/**/*.html.erb
            rubocop:
              - .github/actions/setup-ruby-on-rails/action.yml
              - .github/workflows/minitest--e-navigator.yml
              - .ruby-version
              - ruby-on-rails/e-navigator/.ruby-version
              - ruby-on-rails/e-navigator/Gemfile
              - ruby-on-rails/e-navigator/Gemfile.lock
              - ruby-on-rails/e-navigator/Rakefile
              - ruby-on-rails/e-navigator/rubocop.yml
              - ruby-on-rails/e-navigator/rubocop_todo.yml
              - ruby-on-rails/e-navigator/**/*.rb
              - ruby-on-rails/e-navigator/**/*.rake
            # steep:
              # - .github/actions/setup-ruby-on-rails/action.yml
              # - .github/workflows/minitest--e-navigator.yml
              # - .ruby-version
              # - ruby-on-rails/e-navigator/.ruby-version
              # - ruby-on-rails/e-navigator/Gemfile
              # - ruby-on-rails/e-navigator/Gemfile.lock
              # - ruby-on-rails/e-navigator/Rakefile
              # - ruby-on-rails/e-navigator/Steepfile
              # - ruby-on-rails/e-navigator/**/*.rb
              # - ruby-on-rails/e-navigator/**/*.rbs
              # - ruby-on-rails/e-navigator/**/*.rake
  minitest:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: change-detection
    if: needs.change-detection.outputs.ruby-changes == 'true'
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-ruby-on-rails
        with:
          working-directory: ./ruby-on-rails/e-navigator
          job-name: Minitest
      - name: Minitest
        working-directory: ./ruby-on-rails/e-navigator
        run: bin/rails test
  brakeman:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: change-detection
    if: needs.change-detection.outputs.ruby-changes == 'true'
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-ruby-on-rails
        with:
          working-directory: ./ruby-on-rails/e-navigator
          job-name: Brakeman
      - name: Brakeman
        working-directory: ./ruby-on-rails/e-navigator
        run: bundle exec brakeman --no-pager
  rubocop:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: change-detection
    if: needs.change-detection.outputs.rubocop-changes == 'true'
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-ruby-on-rails
        with:
          working-directory: ./ruby-on-rails/e-navigator
          job-name: RuboCop
      - name: RuboCop
        working-directory: ./ruby-on-rails/e-navigator
        run: bundle exec rubocop
  # steep:
  #   timeout-minutes: 10
  #   runs-on: ubuntu-latest
  #   needs: change-detection
  #   if: needs.change-detection.outputs.steep-changes == 'true'
  #   steps:
  #     - uses: actions/checkout@v6
  #     - uses: ./.github/actions/setup-ruby-on-rails
  #       with:
  #         working-directory: ./ruby-on-rails/e-navigator
  #         job-name: Steep
  #     - name: Steep
  #       working-directory: ./ruby-on-rails/e-navigator
  #       run: |
  #         bundle exec rbs-inline --output sig/generated/ .
  #         bundle exec steep check
