# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: MiniTest
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
      # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
      # change this to (see https://github.com/ruby/setup-ruby#versioning):
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'
      - name: Install GoogleChrome
        run: |
          apt-get update && apt-get install -y curl build-essential libpq-dev libvips libvips-dev vim tree sudo
          sudo chmod -R 777 /etc/apt/sources.list.d/google-chrome.list'
          sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo chmod -R 777 /dev/null
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/google.gpg > /dev/null
          apt-get update && apt-get install -y google-chrome-stable
      - name: Run MiniTest
        run: |
          cd ./ruby-on-rails/restful-api
          chmod -R 777 bin/setup
          bin/setup
          bin/rails test
