# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.

name: RSpec

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.40
        env:
          DB_USERNAME: '${{ secrets.DB_USERNAME }}'
          MYSQL_ROOT_PASSWORD: '${{ secrets.DB_ROOT_PASSWORD }}'
          DB_HOST: '${{ secrets.DB_HOST }}'
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
      # change this to (see https://github.com/ruby/setup-ruby#versioning):
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.5
          bundler-cache: true
      - name: Bundle Install
        working-directory: ./ruby-on-rails/restful-api
        run: bundle install
      - name: Set up Database
        working-directory: ./ruby-on-rails/restful-api
        run: |
          sudo mkdir -p /var/run/mysqld
          sudo chown mysql:mysql /var/run/mysqld
          sudo mysqld_safe --skip-grant-tables &
          bin/setup
      - name: Run RSpec
        working-directory: ./ruby-on-rails/restful-api
        run: bundle exec rspec
