# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby on Rails - Perfect Ruby on Rails

on:
  push:
    branches:
      - master
    paths:
      - .github/actions/setup-ruby-on-rails/action.yml
      - .github/workflows/perfect-ruby-on-rails.yml
      - .ruby-version
      - .node-version
      - ruby-on-rails/perfect-ruby-on-rails/.ruby-version
      - ruby-on-rails/perfect-ruby-on-rails/Gemfile
      - ruby-on-rails/perfect-ruby-on-rails/Gemfile.lock
      - ruby-on-rails/perfect-ruby-on-rails/Rakefile
      - ruby-on-rails/perfect-ruby-on-rails/.rubocop.yml
      - ruby-on-rails/perfect-ruby-on-rails/.rubocop_todo.yml
      - ruby-on-rails/perfect-ruby-on-rails/Steepfile
      - ruby-on-rails/perfect-ruby-on-rails/**/*.rb
      - ruby-on-rails/perfect-ruby-on-rails/**/*.rbs
      - ruby-on-rails/perfect-ruby-on-rails/**/*.rake
      - ruby-on-rails/perfect-ruby-on-rails/**/*.yml
      - ruby-on-rails/perfect-ruby-on-rails/**/*.js
      - ruby-on-rails/perfect-ruby-on-rails/**/*.scss
      - ruby-on-rails/perfect-ruby-on-rails/**/*.css
      - ruby-on-rails/perfect-ruby-on-rails/**/*.html.erb
      - ruby-on-rails/perfect-ruby-on-rails/package.json
      - ruby-on-rails/perfect-ruby-on-rails/pnpm-lock.yaml
  pull_request:
    paths:
      - .github/actions/setup-ruby-on-rails/action.yml
      - .github/workflows/perfect-ruby-on-rails.yml
      - .ruby-version
      - .node-version
      - ruby-on-rails/perfect-ruby-on-rails/.ruby-version
      - ruby-on-rails/perfect-ruby-on-rails/Gemfile
      - ruby-on-rails/perfect-ruby-on-rails/Gemfile.lock
      - ruby-on-rails/perfect-ruby-on-rails/.rubocop.yml
      - ruby-on-rails/perfect-ruby-on-rails/.rubocop_todo.yml
      - ruby-on-rails/perfect-ruby-on-rails/Steepfile
      - ruby-on-rails/perfect-ruby-on-rails/**/*.rb
      - ruby-on-rails/perfect-ruby-on-rails/**/*.rbs
      - ruby-on-rails/perfect-ruby-on-rails/**/*.rake
      - ruby-on-rails/perfect-ruby-on-rails/**/*.yml
      - ruby-on-rails/perfect-ruby-on-rails/**/*.js
      - ruby-on-rails/perfect-ruby-on-rails/**/*.scss
      - ruby-on-rails/perfect-ruby-on-rails/**/*.css
      - ruby-on-rails/perfect-ruby-on-rails/**/*.html.erb
      - ruby-on-rails/perfect-ruby-on-rails/package.json
      - ruby-on-rails/perfect-ruby-on-rails/pnpm-lock.yaml

permissions:
  contents: read
  pull-requests: read

jobs:
  change-detection:
    runs-on: ubuntu-latest
    outputs:
      ruby-changes: ${{ steps.change-detection.outputs.ruby }}
      rubocop-changes: ${{ steps.change-detection.outputs.rubocop}}
      steep-changes: ${{ steps.change-detection.outputs.steep}}
    steps:
      - uses: actions/checkout@v6
      - name: Change Detection
        uses: dorny/paths-filter@v4
        id: change-detection
        with:
          filters: |
            ruby:
              - .github/actions/setup-ruby-on-rails/action.yml
              - .github/workflows/perfect-ruby-on-rails.yml
              - .ruby-version
              - .node-version
              - ruby-on-rails/perfect-ruby-on-rails/.ruby-version
              - ruby-on-rails/perfect-ruby-on-rails/Gemfile
              - ruby-on-rails/perfect-ruby-on-rails/Gemfile.lock
              - ruby-on-rails/perfect-ruby-on-rails/**/*.rb
              - ruby-on-rails/perfect-ruby-on-rails/**/*.rake
              - ruby-on-rails/perfect-ruby-on-rails/**/*.yml
              - ruby-on-rails/perfect-ruby-on-rails/**/*.js
              - ruby-on-rails/perfect-ruby-on-rails/**/*.scss
              - ruby-on-rails/perfect-ruby-on-rails/**/*.css
              - ruby-on-rails/perfect-ruby-on-rails/**/*.html.erb
              - ruby-on-rails/perfect-ruby-on-rails/package.json
              - ruby-on-rails/perfect-ruby-on-rails/pnpm-lock.yaml
            rubocop:
              - .github/actions/setup-ruby-on-rails/action.yml
              - .github/workflows/perfect-ruby-on-rails.yml
              - .ruby-version
              - .node-version
              - ruby-on-rails/perfect-ruby-on-rails/.ruby-version
              - ruby-on-rails/perfect-ruby-on-rails/Gemfile
              - ruby-on-rails/perfect-ruby-on-rails/Gemfile.lock
              - ruby-on-rails/perfect-ruby-on-rails/.rubocop.yml
              - ruby-on-rails/perfect-ruby-on-rails/.rubocop_todo.yml
              - ruby-on-rails/perfect-ruby-on-rails/**/*.rb
              - ruby-on-rails/perfect-ruby-on-rails/**/*.rake
            steep:
              - .github/actions/setup-ruby-on-rails/action.yml
              - .github/workflows/perfect-ruby-on-rails.yml
              - .ruby-version
              - .node-version
              - ruby-on-rails/perfect-ruby-on-rails/.ruby-version
              - ruby-on-rails/perfect-ruby-on-rails/Gemfile
              - ruby-on-rails/perfect-ruby-on-rails/Gemfile.lock
              - ruby-on-rails/perfect-ruby-on-rails/Steepfile
              - ruby-on-rails/perfect-ruby-on-rails/**/*.rb
              - ruby-on-rails/perfect-ruby-on-rails/**/*.rbs
              - ruby-on-rails/perfect-ruby-on-rails/**/*.rake
  minitest:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: change-detection
    services:
      mysql:
        image: mysql:9.6.0
        env:
          DB_USERNAME: '${{ secrets.DB_USERNAME }}'
          MYSQL_ROOT_PASSWORD: '${{ secrets.DB_ROOT_PASSWORD }}'
          DB_HOST: '${{ secrets.DB_HOST }}'
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
    if: needs.change-detection.outputs.ruby-changes == 'true'
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nodejs
        with:
          working-directory: ./ruby-on-rails/perfect-ruby-on-rails
      - uses: ./.github/actions/setup-ruby-on-rails
        with:
          working-directory: ./ruby-on-rails/perfect-ruby-on-rails
          job-name: minitest
      - name: Minitest
        env:
          OAUTH_CLIENT_ID: ${ vars.OAUTH_CLIENT_ID }
          OAUTH_CLIENT_SECRET: ${ vars.OAUTH_CLIENT_SECRET }
        working-directory: ./ruby-on-rails/perfect-ruby-on-rails
        run: bin/rails test
  brakeman:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: change-detection
    if: needs.change-detection.outputs.ruby-changes == 'true'
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-ruby-on-rails
        with:
          working-directory: ./ruby-on-rails/perfect-ruby-on-rails
          job-name: brakeman
      - name: Brakeman
        working-directory: ./ruby-on-rails/perfect-ruby-on-rails
        run: bundle exec brakeman --no-pager
  rubocop:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: change-detection
    if: needs.change-detection.outputs.rubocop-changes == 'true'
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-ruby-on-rails
        with:
          working-directory: ./ruby-on-rails/perfect-ruby-on-rails
          job-name: rubocop
      - name: RuboCop
        working-directory: ./ruby-on-rails/perfect-ruby-on-rails
        run: bundle exec rubocop
  steep:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: change-detection
    if: needs.change-detection.outputs.steep-changes == 'true'
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-ruby-on-rails
        with:
          working-directory: ./ruby-on-rails/perfect-ruby-on-rails
          job-name: steep
      - name: Steep
        working-directory: ./ruby-on-rails/perfect-ruby-on-rails
        run: |
          bundle exec rbs-inline --output sig/generated/ .
          bundle exec steep check
