# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: JavaScript

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/typescript.yml
      - .node-version
      - typescript/package.json
      - typescript/pnpm-lock.yaml
      - typescript/pnpm-workspace.yaml
      - typescript/**/*.ts
  pull_request:
    paths:
      - .github/workflows/typescript.yml
      - .node-version
      - typescript/package.json
      - typescript/pnpm-lock.yaml
      - typescript/pnpm-workspace.yaml
      - typescript/**/*.ts

permissions:
  contents: read
  pull-requests: read

jobs:
  change-detection:
    runs-on: ubuntu-latest
    outputs:
      typescript-changes: ${{ steps.change-detection.outputs.typescript }}
    steps:
      - uses: actions/checkout@v6
      - name: Change Detection
        uses: dorny/paths-filter@v4
        id: change-detection
        with:
          filters: |
            typescript:
              - .github/workflows/typescript.yml
              - .node-version
              - typescript/package.json
              - typescript/pnpm-lock.yaml
              - typescript/pnpm-workspace.yaml
              - typescript/**/*.ts
  jest:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: change-detection
    if: needs.change-detection.outputs.typescript-changes == 'true'
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nodejs
        with:
          working-directory: ./typescript
      - name: Jest
        working-directory: ./typescript
        run: pnpm exec jest
