# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: UnitTest

on:
  push:
    branches: [master]
    paths:
      - ./python
  pull_request:
    branches: [master]
    paths:
      - ./python

permissions:
  contents: read

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.40
        env:
          DB_USERNAME: '${{ vars.DB_USERNAME }}'
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          DB_HOST: '${{ vars.DB_HOST }}'
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping -h 127.0.0.1" --health-interval 20s --health-timeout 10s --health-retries 10
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13.0
      uses: actions/setup-python@v3
      with:
        python-version: 3.13.0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run UnitTest
      working-directory: ./python
      run: python -m unittest discover ./test
